#!/usr/bin/env python
# coding: utf-8

# In[1]:


# Import libraries
from matplotlib import rc
from collections import Counter
from datetime import datetime

import numpy as np
import pandas as pd
import scipy
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import warnings


# In[2]:


# Warning messages options
warnings.filterwarnings("ignore", category=FutureWarning)


# In[3]:


# Pandas options for better showing dataframes
pd.options.mode.chained_assignment = None 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 200)


# In[4]:


# Setting size for plots
fig_dim = (12, 8)


# In[5]:


# Make overarching aesthetic settings for the plots
sns.set_palette("Spectral_r")


# In[ ]:


# ── Global academic style ─────────────────────────────────────────────────────
sns.set_theme(style='ticks', context='paper', font_scale=1.3)
plt.rcParams.update({
    'font.family':        'sans-serif',
    'font.sans-serif':    ['Arial', 'Helvetica', 'DejaVu Sans'],
    'axes.spines.top':    False,
    'axes.spines.right':  False,
    'axes.linewidth':     0.8,
    'xtick.major.width':  0.8,
    'ytick.major.width':  0.8,
    'xtick.direction':    'out',
    'ytick.direction':    'out',
    'legend.frameon':     False,
    'legend.fontsize':    10,
    'savefig.dpi':        300,
    'savefig.bbox':       'tight',
    'pdf.fonttype':       42,
})
# Colorblind-safe palette (Wong 2011) — consistent colour per class
CLASS_COLORS = {
    'MGED':  '#0072B2',
    'RSGED': '#009E73',
    'RSRA':  '#E69F00',
    'WGSRA': '#CC79A7',
}
ROLE_COLORS = {'G': '#4dac26', 'R': '#d01c8b'}
prisec = [ROLE_COLORS['G'], ROLE_COLORS['R']]


# In[ ]:


xlabs      = ["Gene Expression", "RNA-Seq (GEO)", "RNA-Seq (SRA)", "Other SRA"]
cls_order  = ["MGED", "RSGED", "RSRA", "WGSRA"]
cls_colors = [CLASS_COLORS[c] for c in cls_order]


# In[8]:


# Additional functions
def in_list(pot_vec, ref_vec):
    bools = []
    for i in pot_vec:
        if(type(i) == str):
            if(i in ref_vec):
                bools.append(True)
            else:
                bools.append(False)
        else:
            bools.append(False)
    return bools


# In[9]:


# Read datasets
metadata_df = pd.read_csv('../data/metadata_matrix_filtered.csv', low_memory=False)
papers_df = pd.read_csv('../data/papers.csv')

# countries_df and gdp_df are external files not generated by the pipeline
# provide them manually if needed for geographic analysis
# countries_df = pd.read_csv('../data/countries.csv')
# gdp_df = pd.read_csv('../data/gdp.csv')


# In[10]:


# Count unique values for publications ids and accessions
metadata_df[['pmc_ID', 'accession']].nunique()


# In[11]:


# Count unqiue journal names
metadata_df.journal.value_counts()


# In[12]:


total_papers = papers_df[['pmc_ID']].drop_duplicates()
print("Total papers using omics data : ", str(len(total_papers)))


# In[13]:


# Count percent for each repository
rc = Counter(papers_df['class'])
repoCounts = pd.DataFrame.from_dict(rc, orient = 'index').reset_index()
repoCounts = repoCounts.dropna()
repoCounts.columns = ['repository', 'count']
repoCounts['percent'] = repoCounts['count'] / repoCounts['count'].sum()
repoCounts = repoCounts.sort_values(by = "percent", ascending = False)

repoCounts_T = repoCounts.T

cols = repoCounts_T.iloc[0, :]

repoCounts_T.columns = cols
repoCounts_T = repoCounts_T.iloc[2:,:]
repoCounts_T


# In[ ]:


# Figure 1 — horizontal barplot (more precise than pie chart)
counts_by_class = (papers_df.dropna(subset=['class'])
                   .groupby('class')['pmc_ID'].nunique()
                   .reindex(cls_order).fillna(0))
total_n = counts_by_class.sum()
pct = counts_by_class / total_n * 100

fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.barh(xlabs[::-1], pct[::-1], color=cls_colors[::-1], height=0.55)
ax.bar_label(bars, labels=[f'{v:.1f}%' for v in pct[::-1]], padding=4, fontsize=10)
ax.set_xlabel('Percentage of papers (%)')
ax.set_title('Proportion of papers mentioning each dataset type\n'
             f'(n = {int(total_n):,} papers)', pad=10)
ax.set_xlim(0, pct.max() * 1.2)
plt.tight_layout()
plt.savefig('../figures/(Figure 1)pctMentioningPie.png', dpi=300)
plt.show()


# In[15]:


# How many papers reuse and generate
rc


# In[16]:


# How many papers reuse, generate and both?
roles = ['G', 'R', 'B']
rc = {'class': ['generating', 'reusing', 'both']}

for c in ["MGED", "RSGED", "RSRA", "WGSRA"]:
    rec = Counter(papers_df.loc[papers_df['class'] == c, :]['reuse_role'])
    counts = pd.Series(rec).reindex(roles, fill_value=0)
    rc[c] = (counts / counts.sum()).values

reuseCounts = pd.DataFrame(rc).T
reuseCounts.columns = reuseCounts.iloc[0, :]
reuseCounts = reuseCounts.iloc[1:, :]
reuseCounts = reuseCounts.sort_values(by='reusing', ascending=False)
reuseCounts


# In[ ]:


# Figure 2 — stacked barplot, reuse roles by class
fig, ax = plt.subplots(figsize=(7, 5))
x = np.arange(len(cls_order))
width = 0.6

for i, cls in enumerate(cls_order):
    sub = papers_df[papers_df['class'] == cls]
    n = sub['pmc_ID'].nunique()
    pct_r = (sub['reuse_role'] == 'R').sum() / len(sub)
    pct_g = 1 - pct_r
    ax.bar(i, pct_g * 100, width, color=ROLE_COLORS['G'], label='Primary Analysis' if i == 0 else '')
    ax.bar(i, pct_r * 100, width, bottom=pct_g * 100,
           color=ROLE_COLORS['R'], label='Secondary Analysis' if i == 0 else '')
    ax.text(i, 101, f'n={n:,}', ha='center', va='bottom', fontsize=8, color='#444')

ax.axhline(50, color='black', linestyle='--', linewidth=0.8, alpha=0.5)
ax.set_xticks(x)
ax.set_xticklabels(xlabs, rotation=0)
ax.set_ylabel('Proportion of papers (%)')
ax.set_ylim(0, 115)
ax.set_title('Primary vs. secondary analysis by dataset type')
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('../figures/(Figure 2) reuseRoleRepos.png', dpi=300)
plt.show()


# In[18]:


# Preprocess data for reuse and repository distribution across the years
repo_byDate = papers_df.groupby(['year', 'class'])['class'].count().to_frame(name = 'repo_count').reset_index()


# In[19]:


dropme = repo_byDate[repo_byDate['year'] == 2025].index
repo_byDate.drop(dropme, inplace = True)

years = repo_byDate['year'].drop_duplicates().to_list()
years = [int(i) for i in years]


# In[20]:


# NON-CUMULATIVE
z = {'year': repo_byDate['year'], 'repository': 'GEO', 'repo_count': 0}
z2 = {'year': repo_byDate['year'], 'repository': 'SRA', 'repo_count': 0}
z3 = {'year': repo_byDate['year'], 'repository': 'Multiple', 'repo_count': 0}

# Create DataFrames from the dictionaries
zerosGEO = pd.DataFrame(data=z)
zerosSRA = pd.DataFrame(data=z2)
zerosBoth = pd.DataFrame(data=z3)

# Concatenate the DataFrames with repo_byDate for each repository type
gexp_byDate = pd.concat([repo_byDate.loc[repo_byDate['class'] == "MGED", :], zerosGEO], ignore_index=True).groupby(['year'], sort=False).sum().reset_index().sort_values(by='year')
rnaseq_byDate = pd.concat([repo_byDate.loc[repo_byDate['class'] == "RSGED", :], zerosGEO], ignore_index=True).groupby(['year'], sort=False).sum().reset_index().sort_values(by='year')
sra_byDate = pd.concat([repo_byDate.loc[repo_byDate['class'] == "WGSRA", :], zerosSRA], ignore_index=True).groupby(['year'], sort=False).sum().reset_index().sort_values(by='year')
mult_byDate = pd.concat([repo_byDate.loc[repo_byDate['class'] == "Multiple", :], zerosBoth], ignore_index=True).groupby(['year'], sort=False).sum().reset_index().sort_values(by='year')


# In[ ]:


# NON-CUMULATIVE stacked bar — overview (not a numbered figure, kept for EDA)
fig, ax = plt.subplots(figsize=(12, 6))

ax.bar(years, gexp_byDate['repo_count'],   color=CLASS_COLORS['MGED'],  label='Gene Expression')
ax.bar(years, rnaseq_byDate['repo_count'], color=CLASS_COLORS['RSGED'],
       bottom=gexp_byDate['repo_count'], label='RNA-Seq (GEO)')
ax.bar(years, sra_byDate['repo_count'],    color=CLASS_COLORS['WGSRA'],
       bottom=[i+j for i,j in zip(gexp_byDate['repo_count'], rnaseq_byDate['repo_count'])],
       label='Other SRA')
ax.bar(years, mult_byDate['repo_count'],   color='#999999',
       bottom=[i+j+k for i,j,k in zip(gexp_byDate['repo_count'],
                                        rnaseq_byDate['repo_count'],
                                        sra_byDate['repo_count'])],
       label='Multiple')

ax.set_xticks(years)
ax.set_xticklabels(years, rotation=45)
ax.set_title('Yearly breakdown of papers mentioning each type of dataset (non-cumulative)')
ax.set_xlabel('Year')
ax.set_ylabel('Number of papers')
ax.legend(loc='upper left')
plt.tight_layout()
plt.show()


# In[ ]:


# CUMULATIVE time series by class — 2×2 panel (Figure 3)
reuse_byDateGEOexpr  = (papers_df.loc[papers_df['class'] == 'MGED',  :]
                        .groupby(['year','reuse_role'])['reuse_role'].count()
                        .to_frame(name='reuse_count').reset_index())
reuse_byDateRNAseq   = (papers_df.loc[papers_df['class'] == 'RSGED', :]
                        .groupby(['year','reuse_role'])['reuse_role'].count()
                        .to_frame(name='reuse_count').reset_index())
reuse_byDateRSRA     = (papers_df.loc[papers_df['class'] == 'RSRA',  :]
                        .groupby(['year','reuse_role'])['reuse_role'].count()
                        .to_frame(name='reuse_count').reset_index())
reuse_byDateSRAother = (papers_df.loc[papers_df['class'] == 'WGSRA', :]
                        .groupby(['year','reuse_role'])['reuse_role'].count()
                        .to_frame(name='reuse_count').reset_index())

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, (rbd, cls_label, cls_key) in enumerate(zip(
        [reuse_byDateGEOexpr, reuse_byDateRNAseq, reuse_byDateRSRA, reuse_byDateSRAother],
        xlabs, cls_order)):
    ax = axes[idx]
    rbd = rbd[rbd['year'] != 2025].copy()
    years_u = sorted(rbd['year'].drop_duplicates().tolist())

    z_g = pd.DataFrame({'year': years_u, 'reuse_count': 0})
    z_r = pd.DataFrame({'year': years_u, 'reuse_count': 0})

    G_cum = (pd.concat([rbd.loc[rbd['reuse_role']=='G', ['year','reuse_count']], z_g],
                       ignore_index=True)
             .groupby('year')['reuse_count'].sum()
             .sort_index().cumsum().reset_index())
    R_cum = (pd.concat([rbd.loc[rbd['reuse_role']=='R', ['year','reuse_count']], z_r],
                       ignore_index=True)
             .groupby('year')['reuse_count'].sum()
             .sort_index().cumsum().reset_index())

    ax.bar(G_cum['year'], G_cum['reuse_count'],
           color=ROLE_COLORS['G'], label='Primary analysis')
    ax.bar(R_cum['year'], R_cum['reuse_count'],
           bottom=G_cum['reuse_count'],
           color=ROLE_COLORS['R'], label='Secondary analysis')
    ax.set_title(cls_label, fontsize=12, fontweight='bold',
                 color=CLASS_COLORS[cls_key])
    ax.set_xlabel('Year')
    ax.set_ylabel('Cumulative papers')
    ax.tick_params(axis='x', rotation=45)
    if idx == 0:
        ax.legend(loc='upper left', fontsize=9)

fig.suptitle('Cumulative yearly breakdown of analysis roles by dataset type',
             fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig('../figures/(Figure 3) cumTimeSer.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# NON-CUMULATIVE time series by class — 2×2 panel (Figure 4)
cls_start = {'MGED': 2001, 'RSGED': 2007, 'RSRA': 2009, 'WGSRA': 2008}

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for idx, (rbd, cls_label, cls_key) in enumerate(zip(
        [reuse_byDateGEOexpr, reuse_byDateRNAseq, reuse_byDateRSRA, reuse_byDateSRAother],
        xlabs, cls_order)):
    ax = axes[idx]
    rbd = rbd[rbd['year'] != 2025].copy()
    years_u = sorted(rbd['year'].drop_duplicates().tolist())

    z_g = pd.DataFrame({'year': years_u, 'reuse_count': 0})
    z_r = pd.DataFrame({'year': years_u, 'reuse_count': 0})

    G = (pd.concat([rbd.loc[rbd['reuse_role']=='G', ['year','reuse_count']], z_r],
                   ignore_index=True)
         .groupby('year')['reuse_count'].sum().sort_index().reset_index())
    R = (pd.concat([rbd.loc[rbd['reuse_role']=='R', ['year','reuse_count']], z_g],
                   ignore_index=True)
         .groupby('year')['reuse_count'].sum().sort_index().reset_index())

    total = G['reuse_count'] + R['reuse_count']
    pct_g = G['reuse_count'] / total.replace(0, np.nan)
    pct_r = R['reuse_count'] / total.replace(0, np.nan)

    ax.bar(years_u, pct_g * 100, color=ROLE_COLORS['G'], label='Primary analysis')
    ax.bar(years_u, pct_r * 100, bottom=pct_g * 100,
           color=ROLE_COLORS['R'], label='Secondary analysis')
    ax.axhline(50, color='black', linestyle='--', linewidth=0.9, alpha=0.6)
    ax.set_title(cls_label, fontsize=12, fontweight='bold',
                 color=CLASS_COLORS[cls_key])
    ax.set_xlabel('Year')
    ax.set_ylabel('Proportion of papers (%)')
    ax.set_ylim(0, 105)
    ax.tick_params(axis='x', rotation=45)
    if idx == 0:
        ax.legend(loc='lower left', fontsize=9)

fig.suptitle('Non-cumulative yearly breakdown of analysis roles by dataset type',
             fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig('../figures/(Figure 4) nonCumTimeSer.png', dpi=300, bbox_inches='tight')
plt.show()


# In[24]:


# Preprocess for percentage of datasets what are used more than once
mm = metadata_df


# In[ ]:


accs = mm[['converted_accession', 'Date', 'repository', 'reuse_count', 'norm_reuse_count', 'time_public', 'class']].drop_duplicates('converted_accession')


# In[ ]:


# What percentage of datasets are used more than once (re-used at least once)?
accs['wasReused'] = accs['reuse_count'] >= 1
accsPcts = accs.groupby('class', as_index=False).agg({'wasReused': 'mean'})
accsPcts = accsPcts.rename(columns={'wasReused': 'pctReused'})


# In[ ]:


# Figure 5 — proportion of datasets reused, with 95% Wilson CI
from scipy.stats import norm as _norm
z_ci = _norm.ppf(0.975)

n_per_class = accs.groupby('class').size()
p_per_class = accsPcts.set_index('class')['pctReused']

ci_lo, ci_hi = [], []
for cls in cls_order:
    p = p_per_class.get(cls, 0)
    n = n_per_class.get(cls, 1)
    denom = 1 + z_ci**2 / n
    centre = (p + z_ci**2 / (2*n)) / denom
    margin = z_ci * np.sqrt(p*(1-p)/n + z_ci**2/(4*n**2)) / denom
    ci_lo.append(centre - margin)
    ci_hi.append(centre + margin)

p_vals = p_per_class.reindex(cls_order).fillna(0).values
yerr_lo = p_vals - np.array(ci_lo)
yerr_hi = np.array(ci_hi) - p_vals
ns = [f'n={n_per_class.get(c, 0):,}' for c in cls_order]

fig, ax = plt.subplots(figsize=(7, 5))
bars = ax.bar(np.arange(len(cls_order)), p_vals * 100,
              yerr=[yerr_lo * 100, yerr_hi * 100],
              color=cls_colors, error_kw=dict(elinewidth=1.2, capsize=4, capthick=1.2),
              width=0.6)
for i, n in enumerate(ns):
    ax.text(i, (p_vals[i] + yerr_hi[i]) * 100 + 1.5, n,
            ha='center', va='bottom', fontsize=8, color='#444')
ax.set_xticks(np.arange(len(cls_order)))
ax.set_xticklabels(xlabs)
ax.set_xlabel('')
ax.set_ylabel('Proportion of datasets reused (%)')
ax.set_title('Proportion of datasets cited ≥1 time\n(95% Wilson CI)')
ax.set_ylim(0, max(p_vals) * 140)
plt.tight_layout()
plt.savefig('../figures/(Figure 5) pctDataReused.png', dpi=300, bbox_inches='tight')
plt.show()


# In[28]:


# Reuse distribution of reused datasets
accs_filt = accs.loc[accs['reuse_count'] > 0, :]


# In[ ]:


# Figure 6 — RI distribution with n= labels and significance annotations
from scipy.stats import kruskal, mannwhitneyu

groups_ri = {c: accs_filt.loc[accs_filt['class'] == c, 'reuse_count'].values
             for c in cls_order}
kw_stat, kw_p = kruskal(*groups_ri.values())

import itertools as _it
pairs = list(_it.combinations(cls_order, 2))
mw_results = {}
for a, b in pairs:
    _, p = mannwhitneyu(groups_ri[a], groups_ri[b], alternative='two-sided')
    p_bonf = min(p * len(pairs), 1.0)
    mw_results[(a, b)] = p_bonf

def sig_label(p):
    if p < 0.001: return '***'
    if p < 0.01:  return '**'
    if p < 0.05:  return '*'
    return 'ns'

fig, ax = plt.subplots(figsize=(8, 5))
bp = sns.boxplot(data=accs_filt, x='class', y='reuse_count',
                 order=cls_order, showfliers=False,
                 palette=CLASS_COLORS, ax=ax)

for i, cls in enumerate(cls_order):
    n = len(groups_ri[cls])
    ymax = np.percentile(groups_ri[cls], 75) + 1.5 * (
        np.percentile(groups_ri[cls], 75) - np.percentile(groups_ri[cls], 25))
    ax.text(i, ymax * 1.05, f'n={n:,}', ha='center', va='bottom', fontsize=8, color='#444')

ax.set_title(f'Reuse distribution by dataset type\n(Kruskal–Wallis p = {kw_p:.2e})')
ax.set_xticks(range(len(cls_order)))
ax.set_xticklabels(xlabs)
ax.set_xlabel('')
ax.set_ylabel('Reusability Index (RI)')
plt.tight_layout()
plt.savefig('../figures/(Figure 6) reuseDistRepos.png', dpi=300, bbox_inches='tight')
plt.show()


# In[30]:


import statistics


# In[31]:


sraMean = statistics.mean(accs_filt.loc[accs_filt['class'] == "WGSRA"]['reuse_count'])
gexpMean = statistics.mean(accs_filt.loc[accs_filt['class'] == "MGED"]['reuse_count'])
rsraMean = statistics.mean(accs_filt.loc[accs_filt['class'] == "RSRA"]['reuse_count'])
rnaseqMean = statistics.mean(accs_filt.loc[accs_filt['class'] == "RSGED"]['reuse_count'])
print("SRA mean reuse count is " + str(sraMean))
print("RNA-Seq (SRA) mean reuse count is " + str(rsraMean))
print("RNA-Seq (GEO) mean reuse count is " + str(rnaseqMean))
print("Gene expression mean reuse count is " + str(gexpMean))

sraMed = statistics.median(accs_filt.loc[accs_filt['class'] == "WGSRA"]['reuse_count'])
gexpMed = statistics.median(accs_filt.loc[accs_filt['class'] == "MGED"]['reuse_count'])
rnaseqMed = statistics.median(accs_filt.loc[accs_filt['class'] == "RSGED"]['reuse_count'])
print("SRA median reuse count is " + str(sraMed))
print("RNA-Seq median reuse count is " + str(rnaseqMed))
print("Gene expression median reuse count is " + str(gexpMed))


# In[ ]:


# Figure 7 — NRI distribution with n= labels and Kruskal-Wallis p-value
groups_nri = {c: accs_filt.loc[accs_filt['class'] == c, 'norm_reuse_count'].values
              for c in cls_order}
kw_nri_stat, kw_nri_p = kruskal(*groups_nri.values())

fig, ax = plt.subplots(figsize=(8, 5))
sns.boxplot(data=accs_filt, x='class', y='norm_reuse_count',
            order=cls_order, showfliers=False,
            palette=CLASS_COLORS, ax=ax)

for i, cls in enumerate(cls_order):
    n = len(groups_nri[cls])
    ymax = np.percentile(groups_nri[cls], 75) + 1.5 * (
        np.percentile(groups_nri[cls], 75) - np.percentile(groups_nri[cls], 25))
    ax.text(i, ymax * 1.05, f'n={n:,}', ha='center', va='bottom', fontsize=8, color='#444')

ax.set_title(f'Time-normalized reuse distribution by dataset type\n'
             f'(Kruskal–Wallis p = {kw_nri_p:.2e})')
ax.set_xticks(range(len(cls_order)))
ax.set_xticklabels(xlabs)
ax.set_xlabel('')
ax.set_ylabel('Normalized Reusability Index (NRI)')
plt.tight_layout()
plt.savefig('../figures/(Figure 7) reuseDistRepos_norm.png', dpi=300, bbox_inches='tight')
plt.show()


# In[33]:


paps = papers_df
paps


# In[34]:


pc = Counter(metadata_df['pmc_ID'])

papsCounts = pd.DataFrame.from_dict(pc, orient = 'index').reset_index()
papsCounts.columns = ['pmc_ID', 'count']
papsCounts = papsCounts.sort_values('count', ascending = False)
papsCounts.head(10)


# In[35]:


mm_filt = pd.merge(paps, mm, how = 'left', on = ['pmc_ID', 'repository', 'reuse_role', 'class'])
mm_filt.sample(5)


# In[36]:


# Let's found top 10 reused datasets and papers for them
top_10_accessions = mm_filt['converted_accession'].value_counts().head(10).index
top_10_df = mm_filt[mm_filt['converted_accession'].isin(top_10_accessions)]
top_10_df['converted_accession'].value_counts()
top_10_df['converted_accession'].value_counts().to_csv('../data/top_10_df.csv')


# In[37]:


# Let's found top 100 reused datasets and papers for them
top_100_accessions = mm_filt['converted_accession'].value_counts().head(100).index
top_100_df = mm_filt[mm_filt['converted_accession'].isin(top_100_accessions)]
top_100_df['converted_accession'].value_counts()
top_100_df['converted_accession'].value_counts().to_csv('../data/top_100_df.csv')


# In[ ]:


# ── Journal analysis ─────────────────────────────────────────────────────────

# Top 20 journals by reuse volume (number of reusing papers)
reusers = metadata_df[metadata_df['reuse_role'] == 'R']
top_journals_reuse = (reusers.groupby('journal')['pmc_ID']
                      .nunique()
                      .sort_values(ascending=False)
                      .head(20)
                      .reset_index())
top_journals_reuse.columns = ['journal', 'n_reusing_papers']
print("Top 20 journals by number of reusing papers:")
print(top_journals_reuse.to_string(index=False))
print()

# Top 20 journals by reuse rate (% papers that are reusers, min 50 papers)
journal_roles = (metadata_df.groupby(['journal', 'pmc_ID'])['reuse_role']
                 .apply(lambda x: 'R' if (x == 'R').any() else 'G')
                 .reset_index())
journal_roles.columns = ['journal', 'pmc_ID', 'role']
journal_stats = journal_roles.groupby('journal').agg(
    total=('pmc_ID', 'nunique'),
    reusers=('role', lambda x: (x == 'R').sum())
).reset_index()
journal_stats['reuse_rate'] = journal_stats['reusers'] / journal_stats['total']
top_reuse_rate = (journal_stats[journal_stats['total'] >= 50]
                  .sort_values('reuse_rate', ascending=False)
                  .head(20))
print("Top 20 journals by reuse rate (min 50 papers):")
print(top_reuse_rate[['journal','total','reusers','reuse_rate']].to_string(index=False))
top_journals_reuse.to_csv('../data/top_journals_reuse.csv', index=False)
top_reuse_rate.to_csv('../data/top_journals_reuse_rate.csv', index=False)


# In[ ]:


# ── Statistical tests ────────────────────────────────────────────────────────
from scipy import stats

accs_stats = metadata_df[['converted_accession', 'class', 'reuse_count']].drop_duplicates('converted_accession')
accs_stats = accs_stats[accs_stats['reuse_count'] > 0]

groups = {c: accs_stats.loc[accs_stats['class'] == c, 'reuse_count'].values
          for c in ['MGED', 'RSGED', 'RSRA', 'WGSRA']}

# Kruskal-Wallis: overall difference between classes
kw_stat, kw_p = stats.kruskal(*groups.values())
print(f"Kruskal-Wallis H = {kw_stat:.1f}, p = {kw_p:.2e}")
print()

# Pairwise Mann-Whitney U with Bonferroni correction (6 pairs)
import itertools
pairs = list(itertools.combinations(['MGED', 'RSGED', 'RSRA', 'WGSRA'], 2))
n_tests = len(pairs)
print(f"{'Pair':<22} {'U':>12} {'p (raw)':>12} {'p (Bonf)':>12} {'sig':>4}")
print("-" * 65)
for a, b in pairs:
    u, p = stats.mannwhitneyu(groups[a], groups[b], alternative='two-sided')
    p_bonf = min(p * n_tests, 1.0)
    sig = '***' if p_bonf < 0.001 else ('**' if p_bonf < 0.01 else ('*' if p_bonf < 0.05 else 'ns'))
    print(f"{a} vs {b:<12} {u:>12.0f} {p:>12.2e} {p_bonf:>12.2e} {sig:>4}")

print()

# Spearman trend: reuse_count vs year of generator paper
gens_trend = metadata_df[metadata_df['reuse_role'] == 'G'].copy()
gens_trend['year'] = pd.to_datetime(gens_trend['pmc_date'], errors='coerce').dt.year
gens_trend = gens_trend.dropna(subset=['year', 'reuse_count'])
rho, p_trend = stats.spearmanr(gens_trend['year'], gens_trend['reuse_count'])
print(f"Spearman trend (reuse_count vs generator year): rho = {rho:.3f}, p = {p_trend:.2e}")


# In[ ]:


# ── Figure 11: Top 20 journals by reuse volume ───────────────────────────────
top_j = pd.read_csv('../data/top_journals_reuse.csv')

fig, ax = plt.subplots(figsize=(10, 8))
bars = ax.barh(top_j['journal'][::-1], top_j['n_reusing_papers'][::-1],
               color=sns.color_palette('Spectral_r', len(top_j)))
ax.set_xlabel('Number of secondary analysis papers')
ax.set_title('Top 20 journals by secondary analysis volume')
ax.bar_label(bars, padding=3, fontsize=9)
ax.set_xlim(0, top_j['n_reusing_papers'].max() * 1.18)
plt.tight_layout()
plt.savefig('../figures/(Figure 11) topJournals_reuse.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 10: Reuse rate trend — all 4 classes on one plot ──────────────────
trend_df = (papers_df[papers_df['year'].between(2004, 2024)]
            .groupby(['year', 'class', 'reuse_role'])['pmc_ID']
            .nunique()
            .reset_index())
trend_df.columns = ['year', 'class', 'reuse_role', 'n']

pivot = trend_df.pivot_table(index=['year', 'class'], columns='reuse_role',
                              values='n', fill_value=0).reset_index()
pivot['total'] = pivot.get('G', 0) + pivot.get('R', 0)
pivot['pct_R']  = pivot.get('R', 0) / pivot['total'].replace(0, np.nan)

fig, ax = plt.subplots(figsize=(11, 6))

for cls, label in zip(cls_order, xlabs):
    sub = pivot[pivot['class'] == cls].sort_values('year')
    ax.plot(sub['year'], sub['pct_R'] * 100,
            marker='o', markersize=4, linewidth=2,
            color=CLASS_COLORS[cls], label=label)

ax.axhline(50, color='black', linestyle='--', linewidth=0.9, alpha=0.5)
ax.set_xlim(2004, 2024)
ax.set_ylim(0, 100)
ax.set_xlabel('Year')
ax.set_ylabel('% papers performing secondary analysis')
ax.set_title('Growth of secondary analysis over time by dataset type')
ax.legend(loc='upper left', fontsize=10)
ax.yaxis.set_major_formatter(mpl.ticker.PercentFormatter())
plt.tight_layout()
plt.savefig('../figures/(Figure 10) reuseRate_trend.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 9: pub_delay distribution for generators ──────────────────────────
gens_delay = metadata_df[
    (metadata_df['reuse_role'] == 'G') &
    metadata_df['pub_delay'].notna()
].drop_duplicates(subset=['pmc_ID', 'converted_accession']).copy()

fig, axes = plt.subplots(1, 4, figsize=(18, 5), sharey=False)
WINDOW = 270

for ax, cls, color in zip(axes, cls_order, cls_colors):
    data = gens_delay.loc[gens_delay['class'] == cls, 'pub_delay'].clip(-500, 500)
    ax.hist(data, bins=60, color=color, edgecolor='white', linewidth=0.4)
    ax.axvline(-WINDOW, color='gray', linestyle=':', linewidth=1)
    ax.axvline( WINDOW, color='gray', linestyle=':', linewidth=1)
    ax.axvline(0, color='black', linestyle='--', linewidth=1, label='Day 0')
    pct_inside = (data.abs() <= WINDOW).mean() * 100
    ax.set_title(xlabs[cls_order.index(cls)], fontsize=12)
    ax.set_xlabel('Days (paper date − dataset deposit date)')
    ax.set_ylabel('Generators' if cls == 'MGED' else '')
    ax.legend([f'±270-day window\n({pct_inside:.0f}% inside)'], fontsize=8)

fig.suptitle('Publication delay of generator papers\n(positive = paper after data deposit)', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('../figures/(Figure 9) pubDelay_generators.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 8: RI distribution (log-scale histogram, power-law shape) ─────────
accs_unique = metadata_df[['converted_accession', 'class', 'reuse_count']].drop_duplicates('converted_accession')
accs_ri = accs_unique[accs_unique['reuse_count'] > 0].copy()

fig, axes = plt.subplots(1, 4, figsize=(18, 5), sharey=False)

for ax, cls, color in zip(axes, cls_order, cls_colors):
    data = accs_ri.loc[accs_ri['class'] == cls, 'reuse_count']
    bins = np.logspace(0, np.log10(data.max() + 1), 40)
    ax.hist(data, bins=bins, color=color, edgecolor='white', linewidth=0.4)
    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_title(xlabs[cls_order.index(cls)], fontsize=12, fontweight='bold', color=color)
    ax.set_xlabel('Reusability Index (RI)')
    ax.set_ylabel('Number of datasets' if cls == 'MGED' else '')
    med = data.median()
    ax.axvline(med, color='black', linestyle='--', linewidth=1.2, label=f'Median = {med:.0f}')
    ax.legend(fontsize=9)

fig.suptitle('RI distribution of reused datasets (log–log scale)', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('../figures/(Figure 8) RI_distribution_loglog.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:





# In[ ]:


# Figure 12: Cumulative reuse uptake
REFERENCE_DATE_TS = pd.Timestamp('2026-01-01')

_md = metadata_df.copy()
_md['pmc_date_dt']        = pd.to_datetime(_md['pmc_date'],        errors='coerce')
_md['repository_date_dt'] = pd.to_datetime(_md['repository_date'], errors='coerce')

first_reuse = (_md[_md['reuse_role'] == 'R']
               .groupby('converted_accession')['pmc_date_dt']
               .min().reset_index()
               .rename(columns={'pmc_date_dt': 'first_reuse_date'}))

accs_meta = (_md[['converted_accession', 'repository_date_dt', 'class']]
             .drop_duplicates('converted_accession'))

surv_df = accs_meta.merge(first_reuse, on='converted_accession', how='left')
surv_df['was_reused']    = surv_df['first_reuse_date'].notna()
surv_df['days_to_event'] = np.where(
    surv_df['was_reused'],
    (surv_df['first_reuse_date']   - surv_df['repository_date_dt']).dt.days,
    (REFERENCE_DATE_TS             - surv_df['repository_date_dt']).dt.days)
surv_df = surv_df[surv_df['days_to_event'] > 0].dropna(subset=['days_to_event'])

def km_estimator(times, events):
    df = pd.DataFrame({'t': times, 'e': events}).sort_values('t').reset_index(drop=True)
    n_at_risk = len(df)
    t_out, S_out = [0.0], [1.0]
    for t, grp in df.groupby('t', sort=True):
        d = grp['e'].sum()
        if n_at_risk > 0 and d > 0:
            S_out.append(S_out[-1] * (1 - d / n_at_risk))
            t_out.append(t)
        n_at_risk -= len(grp)
    return np.array(t_out), np.array(S_out)

fig, ax = plt.subplots(figsize=(10, 6))
for yr in [1, 3, 5, 10]:
    ax.axvline(yr, color='#e0e0e0', linewidth=0.9, zorder=0)

for cls, color, label in zip(cls_order, cls_colors, xlabs):
    sub = surv_df[surv_df['class'] == cls]
    t_arr, S_arr = km_estimator(sub['days_to_event'].values / 365,
                                sub['was_reused'].values)
    uptake = (1 - S_arr) * 100
    n = len(sub)

    # % at yr 5 from the KM curve itself
    mask5 = t_arr <= 5
    pct5 = uptake[mask5][-1] if mask5.any() else 0
    mask10 = t_arr <= 10
    pct10 = uptake[mask10][-1] if mask10.any() else 0

    ax.step(t_arr, uptake, where='post', color=color, linewidth=2.2,
            label=f'{label}  ({pct10:.0f}% by yr 10, n={n:,})')
    ax.annotate(f'{pct5:.0f}%', xy=(5, pct5), fontsize=8.5, color=color,
                xytext=(5, 0), textcoords='offset points', va='center')

ax.set_xlabel('Years since data deposit')
ax.set_ylabel('Cumulative % of datasets reused')
ax.set_title('How quickly do datasets find a second use?')
ax.set_xlim(0, 15)
ax.set_ylim(0, 85)
ax.set_xticks([0, 1, 3, 5, 7, 10, 15])
ax.legend(loc='upper left', fontsize=9)
sns.despine(ax=ax)
plt.tight_layout()
plt.savefig('../figures/(Figure 12) survival_first_reuse.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 13: Heatmap — deposit year × reuse year ───────────────────────────
_reuse_events = _md[_md['reuse_role'] == 'R'].copy()
_reuse_events['deposit_year'] = _reuse_events['repository_date_dt'].dt.year.astype('Int64')
_reuse_events['reuse_year']   = _reuse_events['pmc_date_dt'].dt.year.astype('Int64')

_re = (_reuse_events
       .dropna(subset=['deposit_year', 'reuse_year'])
       .query('2003 <= deposit_year <= 2021 and 2004 <= reuse_year <= 2024'))

heat_raw = (_re.groupby(['deposit_year', 'reuse_year'])
             .size().unstack(fill_value=0).astype(int))

# Row-normalize
heat_norm = heat_raw.div(heat_raw.sum(axis=1), axis=0).fillna(0) * 100

# Mask impossible cells (reuse before deposit)
mask = np.zeros(heat_norm.shape, dtype=bool)
dep_years = heat_norm.index.tolist()
reu_years = heat_norm.columns.tolist()
for i, dy in enumerate(dep_years):
    for j, ry in enumerate(reu_years):
        if ry <= dy:
            mask[i, j] = True

fig, ax = plt.subplots(figsize=(12, 8))

# Integer tick labels
xticklabels = [str(y) if y % 2 == 0 else '' for y in reu_years]
yticklabels = [str(y) if y % 2 == 0 else '' for y in dep_years]

sns.heatmap(heat_norm, mask=mask, cmap='YlOrRd', ax=ax,
            cbar_kws={"label": "% of cohort reuse events"},
            linewidths=0, rasterized=True,
            xticklabels=xticklabels, yticklabels=yticklabels)

# Clean diagonal: deposit year = reuse year
diag_pts = [(reu_years.index(y) + 0.5, dep_years.index(y) + 0.5)
            for y in dep_years if y in reu_years]
if diag_pts:
    dx, dy_pos = zip(*diag_pts)
    ax.plot(dx, dy_pos, color='white', linewidth=1.5, linestyle='--',
            label='deposit yr = reuse yr', zorder=5)
    ax.legend(loc='upper left', fontsize=9)

ax.set_xlabel('Year of reuse (paper date)')
ax.set_ylabel('Year of data deposit')
ax.set_title('When are datasets reused?\n(row-normalised: % of all reuse events per deposit cohort)')
ax.tick_params(axis='x', rotation=45)
ax.tick_params(axis='y', rotation=0)
plt.tight_layout()
plt.savefig('../figures/(Figure 13) heatmap_deposit_reuse_year.png',
            dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 14: % of datasets reused by year of deposit ───────────────────────
_accs_vint = (accs
              .merge(metadata_df[['converted_accession', 'repository_date']]
                     .drop_duplicates('converted_accession'),
                     on='converted_accession', how='left'))
_accs_vint['deposit_year'] = pd.to_datetime(_accs_vint['repository_date'],
                                             errors='coerce').dt.year
_accs_vint['was_reused']   = (_accs_vint['reuse_count'] >= 1)
_accs_vint = _accs_vint[_accs_vint['deposit_year'].between(2003, 2022)]

fig, ax = plt.subplots(figsize=(11, 6))

for cls, color, label in zip(cls_order, cls_colors, xlabs):
    sub = _accs_vint[_accs_vint['class'] == cls]
    stats = (sub.groupby('deposit_year')
               .agg(n=('was_reused', 'count'),
                    pct=('was_reused', 'mean'))
               .reset_index()
               .sort_values('deposit_year'))
    # Wilson CI
    from scipy.stats import norm as _norm
    z = _norm.ppf(0.975)
    p, n = stats['pct'].values, stats['n'].values
    margin = z * np.sqrt(p * (1 - p) / n)
    ax.plot(stats['deposit_year'], p * 100,
            color=color, linewidth=2.2, marker='o', markersize=4, label=label)
    ax.fill_between(stats['deposit_year'],
                    (p - margin) * 100, (p + margin) * 100,
                    color=color, alpha=0.12)

ax.set_xlabel('Year of data deposit')
ax.set_ylabel('% of datasets reused at least once')
ax.set_title('Older datasets are more likely to have been reused '
             '(shading = 95% Wilson CI)')
ax.set_xlim(2003, 2022)
ax.set_xticks(range(2004, 2023, 2))
ax.set_ylim(0, 85)
ax.legend(loc='upper right', fontsize=10)
sns.despine(ax=ax)
plt.tight_layout()
plt.savefig('../figures/(Figure 14) RI_vs_timepublic.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# Figure 15: Top species by % reused
_sp_all = (metadata_df
           .drop_duplicates('converted_accession')
           .dropna(subset=['species'])
           .copy())
_sp_all['species_clean'] = _sp_all['species'].str.strip()
_sp_all = _sp_all[_sp_all['species_clean'] != '']
_sp_all['was_reused'] = (_sp_all['reuse_count'] >= 1)

sp_stats = (_sp_all.groupby('species_clean')
             .agg(n=('converted_accession', 'count'),
                  pct_reused=('was_reused', 'mean'),
                  mean_ri=('reuse_count', 'mean'))
             .reset_index())

top_sp = (sp_stats[sp_stats['n'] >= 200]
          .sort_values('pct_reused', ascending=False)
          .head(15))

from scipy.stats import norm as _norm2
z2 = _norm2.ppf(0.975)
p2, n2 = top_sp['pct_reused'].values, top_sp['n'].values
ci = z2 * np.sqrt(p2 * (1 - p2) / n2)

fig, ax = plt.subplots(figsize=(10, 7))
pal = sns.color_palette('Blues_r', len(top_sp))
bars = ax.barh(range(len(top_sp)),
               top_sp['pct_reused'].values[::-1] * 100,
               xerr=ci[::-1] * 100,
               color=pal,
               error_kw=dict(elinewidth=1, capsize=3), height=0.65)

ax.set_yticks(range(len(top_sp)))
ax.set_yticklabels(
    [f"{s}  (n={int(n):,})"
     for s, n in zip(top_sp['species_clean'].values[::-1],
                     top_sp['n'].values[::-1])],
    fontsize=9)

# Annotate mean RI only if meaningfully > 1
for i, (p, ri, ci_v) in enumerate(zip(top_sp['pct_reused'].values[::-1],
                                       top_sp['mean_ri'].values[::-1],
                                       ci[::-1])):
    if ri > 1.5:
        ax.text(p * 100 + ci_v * 100 + 0.5, i,
                f'mean RI = {ri:.0f}', va='center', fontsize=8, color='#333')

ax.set_xlabel('% of datasets reused at least once')
ax.set_title("Top species by dataset reuse rate (>=200 datasets; 95% CI)")
ax.set_xlim(0, 80)
sns.despine(ax=ax)
plt.tight_layout()
plt.savefig('../figures/(Figure 15) top_species_ri.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# Figure 16: Publication timing vs reuse rate
from scipy.stats import norm as _norm3, chi2_contingency as _chi2

_gens16 = (metadata_df[(metadata_df['reuse_role'] == 'G') &
                        metadata_df['pub_delay'].notna()]
           .drop_duplicates('converted_accession')
           .copy())
_gens16['was_reused'] = (_gens16['reuse_count'] >= 1)

def delay_cat(d):
    if d > 90:   return 'Data first'
    if d >= -90: return 'Concurrent'
    return 'Paper first'

_gens16['delay_cat'] = _gens16['pub_delay'].apply(delay_cat)
cat_order16 = ['Data first', 'Concurrent', 'Paper first']
cat_colors16 = ['#2ca02c', '#aec7e8', '#d62728']
z16 = _norm3.ppf(0.975)

fig, axes = plt.subplots(1, 4, figsize=(15, 6), sharey=True)

for ax, cls, label in zip(axes, cls_order, xlabs):
    sub = _gens16[_gens16['class'] == cls]
    pcts, yerr_lo, yerr_hi, ns = [], [], [], []

    for cat in cat_order16:
        grp = sub[sub['delay_cat'] == cat]
        n = len(grp)
        p = grp['was_reused'].mean() if n > 0 else 0
        denom = 1 + z16**2 / max(n, 1)
        centre = (p + z16**2 / (2*max(n,1))) / denom
        margin = (z16 * np.sqrt(p*(1-p)/max(n,1) + z16**2/(4*n**2)) / denom
                  if n > 0 else 0)
        pcts.append(p * 100)
        yerr_lo.append((centre - margin) * 100)
        yerr_hi.append((centre + margin) * 100)
        ns.append(n)

    pcts_arr = np.array(pcts)
    err_lo = pcts_arr - np.array(yerr_lo)
    err_hi = np.array(yerr_hi) - pcts_arr

    ax.bar(range(3), pcts_arr, color=cat_colors16, width=0.6,
           yerr=[err_lo, err_hi],
           error_kw=dict(elinewidth=1.2, capsize=4))
    for i, (p, n) in enumerate(zip(pcts_arr, ns)):
        ax.text(i, p + err_hi[i] + 0.5, f'n={n:,}',
                ha='center', va='bottom', fontsize=7, color='#555')

    # Chi-squared
    ct = np.array([[sub.loc[sub['delay_cat']==c, 'was_reused'].sum(),
                    (sub['delay_cat']==c).sum()
                    - sub.loc[sub['delay_cat']==c, 'was_reused'].sum()]
                   for c in cat_order16])
    if ct.min() > 0:
        _, p_chi, _, _ = _chi2(ct)
        sig = '***' if p_chi < 0.001 else ('**' if p_chi < 0.01 else ('*' if p_chi < 0.05 else 'ns'))
        ax.text(0.5, 0.97, f'chi2 {sig}', transform=ax.transAxes,
                ha='center', va='top', fontsize=10, fontweight='bold')

    ax.set_xticks(range(3))
    ax.set_xticklabels(cat_order16, fontsize=10, rotation=15, ha='right')
    ax.set_title(label, fontsize=11, fontweight='bold', color=CLASS_COLORS[cls])
    if cls == 'MGED':
        ax.set_ylabel('% of datasets reused at least once')
    sns.despine(ax=ax)

ax.text(-0.05, -0.18,
        'Data first: data deposited >3 months before paper.  '
        'Paper first: paper published >3 months before data.',
        transform=axes[0].transAxes, fontsize=7.5, color='#555',
        ha='left', va='top')

fig.suptitle('Effect of publication timing on reuse rate varies by data type',
             fontsize=12, y=1.02)
plt.tight_layout()
plt.savefig('../figures/(Figure 16) pubdelay_vs_ri.png', dpi=300, bbox_inches='tight')
plt.show()


# In[ ]:


# ── Figure 17: Reuse inequality — proportional stacked bar ───────────────────
tiers = [
    ('Never reused (RI = 0)',    lambda s: s == 0,            '#d9d9d9'),
    ('Low reuse (RI 1–9)',       lambda s: (s >= 1) & (s <= 9),  '#74c476'),
    ('Moderate (RI 10–99)',      lambda s: (s >= 10) & (s <= 99), '#fd8d3c'),
    ('High reuse (RI >= 100)',    lambda s: s >= 100,           '#c7191c'),
]

fig, ax = plt.subplots(figsize=(9, 6))
x = np.arange(len(cls_order))
bottoms = np.zeros(len(cls_order))

for tier_label, condition, color in tiers:
    heights, counts = [], []
    for cls in cls_order:
        s = accs[accs['class'] == cls]['reuse_count']
        n = len(s)
        cnt = condition(s).sum()
        heights.append(cnt / n * 100)
        counts.append(cnt)
    heights = np.array(heights)
    ax.bar(x, heights, bottom=bottoms, color=color, width=0.6,
           label=tier_label, edgecolor='white', linewidth=0.5)
    for i, (h, b, cnt) in enumerate(zip(heights, bottoms, counts)):
        if h >= 4:
            ax.text(i, b + h / 2, f'{h:.0f}% ({cnt:,})',
                    ha='center', va='center', fontsize=8.5,
                    fontweight='bold', color='white' if h > 10 else 'black')
    bottoms += heights

ax.set_xticks(x)
ax.set_xticklabels(xlabs, fontsize=11)
ax.set_ylabel('% of datasets')
ax.set_ylim(0, 108)
ax.set_title('Most datasets are never reused '
             'Gene Expression data is the exception')
ax.legend(loc='upper right', fontsize=9, framealpha=0.9)

for i, cls in enumerate(cls_order):
    n = len(accs[accs['class'] == cls])
    ax.text(i, -3.5, f'n = {n:,}', ha='center', va='top', fontsize=8, color='#444')

sns.despine(ax=ax)
plt.tight_layout()
plt.savefig('../figures/(Figure 17) reuse_funnel.png', dpi=300, bbox_inches='tight')
plt.show()

